### PR TITLE
feat: support re-use space in the tree

### PR DESCRIPTION
**Pull request by M-Adoo**
This pr have two part change:

1.  Support re-use the space in the tree, nodes will be re-used after them have been removed.
2. Release the data when the node be removed. Otherwise it may cause memory leaks if the data hold a ref count of other data.

### CODE REVIEW

**Review by saschagrunert — COMMENTED** [review]
That's pretty nice, thank you! :pray: 

Let me check if I can fix the CI in another PR.

**Comment by saschagrunert** [comment]
@M-Adoo may I ask you to rebase to fix the failing CI?

**Comment by M-Adoo** [comment]
@saschagrunert I had rebased it. Also let the implement not depend on std now.

**Review by saschagrunert — APPROVED** [review]
LGTM, thanks!

**Pull request merged**
