### PR TITLE
Update version to v4.0.0

### PR DESCRIPTION
**Pull request by saschagrunert**
This is my reminder to release the next major version soon.

@lo48576 do you have anything else planned before we’re ready to release version 4?

### CODE REVIEW

**Comment by lo48576** [comment]
Thank you for asking.
I'm trying to implement #12 (it is breaking change), but it may take time and I'm not sure it is worth merging.

Additionally, I'm thinking about some braking changes, for example:

* Not using `failure` crate
    + Errors of indextree is quite simple. `failure` seems too powerful.
* Monomorphize node manipulation functions
    + Tree traversal and manipulations (such as insert, remove, and iteration) essentially does not need the type parameter `T`, because they care only neighbors, but ignores data.
    + I don't know this is possible.

By the way, is it necessary to bump major version?
It seems there are no breaking changes since 3.3.0.
(Changes observable by the users is "panic instead of returning error, when indextree has a bug". I think 3.3.1 or 3.4.0 is enough.)

**Comment by saschagrunert** [comment]
Okay thanks. The major version bump was more or less just speculation since I thought you’re already working on further (maybe breaking) improvements. 

Keep it up, I really enjoy your contributions. :) 

We can wait with the next release, so let’s keep this PR as slight reminder that we need a new version in the not so far future...

**Comment by lo48576** [comment]
I have no idea at this time what it looks like if node relations manipulation is monomorphized...
I believe I've sent all breaking changes I can think now.
Thank you for merging them! :smile:

**Comment by saschagrunert** [comment]
Cool 😎 thank you for the extensive contributions. Let’s kick of a new release then.

**Comment by lo48576** [comment]
@saschagrunert Found typo in [release note](https://github.com/saschagrunert/indextree/releases/tag/4.0.0):
> Drop dependency for failure crate, and make `NodeId::remove()` internal

remove() became infallible, but not internal 😉

**Comment by saschagrunert** [comment]
> @saschagrunert Found typo in [release note](https://github.com/saschagrunert/indextree/releases/tag/4.0.0):
> 
> > Drop dependency for failure crate, and make `NodeId::remove()` internal
> 
> remove() became infallible, but not internal 😉

Thanks for the hint, fixed it. :)

**Pull request merged**
