### PR TITLE
Add  `remove_subtree`

### PR DESCRIPTION
**Pull request by M-Adoo**

### CODE REVIEW

**Review by saschagrunert — APPROVED** [review]
Thank you 🙏! May I ask you to add a unit test and fix the CI?

**Comment by lo48576** [comment]
cc: #53

**Comment by M-Adoo** [comment]
@saschagrunert  not use `std` now and the fixed the ci. Not add a unit test because the document already contain it.

**Comment by saschagrunert** [comment]
Thank you!

**Pull request merged**
